fail_fast: true
repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        name: shellcheck
  - repo: local
    hooks:
      - id: test
        name: test
        entry: task test
        language: system
        types: [shell]
        pass_filenames: false
