name: Shellcheck

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  ruff:
    name: Run codequality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Task
        uses: go-task/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Shellcheck
        run: task shellcheck
